name: Deploy Lambda Module

on:
  push:
    branches:
      - main
    paths:
      - 'dev/**'
      - 'lambda/**'
      - 'modules/**'

jobs:
  terraform-deploy:
    name: Terraform Deploy
    runs-on: [self-hosted, ec2-runner]

    env:
      AWS_REGION: us-east-1
      ROLE_ARN: arn:aws:iam::123456789012:role/GitHubActionsDeployRole

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform Init
        run: terraform init
        working-directory: dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: dev

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: dev

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: dev
