name: test

on:
  workflow_dispatch:
    inputs:
      tf_apply:
        description: run terraform apply
        default: 'false'
  push:
    paths:
      - '.github/workflows/test.yml'
      - 'dev/us-east-1/**'
      - 'modules/**'
      - 'lambda/**'

      
permissions:
  contents: read

jobs:
  Terraform:
    runs-on: [self-hosted]

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

       # Python setup for runner
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

       # Clean old zips
      - name: Clean old ZIP files
        run: |
          echo "Removing old ZIP files from previous runs..."
          find lambda/lambda_layer -type f -name "*.zip" -delete  
  
      # Build Lambda Layer
      - name: Build Lambda Layer
        run: |
          chmod +x ./build_layer.sh
          ./build_layer.sh  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.12  

      - name: Terraform Format
        run: terraform fmt -recursive -check -diff -write=false .

      - name: Terraform Init
        run: |
          cd dev/us-east-1 && terraform init

      - name: Terraform Plan
        run: cd dev/us-east-1 && terraform plan -input=false
      # tf apply
      - name: Terraform Apply
        if: ((github.ref == 'refs/heads/main' && github.event_name == 'push')||(github.ref == 'refs/heads/main' && github.event_name == 'workflow_dispatch' && github.event.inputs.tf_apply == 'true'))
        run: cd dev/us-east-1 && terraform apply -auto-approve -input=false

  
          

